# baseURL = "https://Lynx_JiaqiCheng.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Lynx Jiaqi Cheng"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
    name = "Jiaqi Cheng"
    headline = "A Full Stack Engineer"
    image = "img/JiaqiCheng.jpg"  # path relative to static directory

  links = [
    { email = "mailto:jiaqicheng1104@gmail.com" },
    # { link = "https://link-to-some-website.com/" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    { github = "https://github.com/jiaqicheng1104" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/username" },
    { linkedin = "https://www.linkedin.com/in/jiaqi-cheng-2b637a190/" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"